version: "3.2"

services:
    db:
        image: mysql:5.7
        container_name: aloner-db
        restart: on-failure:2
        environment:
            MYSQL_ROOT_PASSWORD: root
            # From docker documentation (https://docs.docker.com/compose/env-file). Compose supports declaring default
            # environment variables in an environment file named .env placed in the folder where the docker-compose command is executed
            MYSQL_DATABASE: "${DATABASE_SCHEMA}"
            MYSQL_USER: "${DATABASE_USER}"
            MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
        ports:
            - "8002:3306"
        volumes:
            - ./.docker/db:/etc/mysql/conf.d:ro
            - container-volume:/var/lib/mysql

    webserver:
        image: nginx:alpine
        container_name: aloner-webserver
        restart: on-failure:2
        links:
            - app
        volumes:
            - .:/application
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"

    app:
        build: ./.docker/app
        container_name: aloner-app
        restart: on-failure:2
        links:
            - db
        environment:
            # XDebug for PHPStorm.
            # To map paths between PHPStorm project and docker app you need to create server
            # named "aloner" with redirect path under Setting -> PHP -> Servers
            PHP_IDE_CONFIG: "serverName=aloner"
        volumes:
            - .:/application
            - ./.docker/app/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
            - ./.docker/app/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf

    mercure:
        container_name: aloner-mercure
        restart: on-failure:2
        image: dunglas/mercure
        environment:
            JWT_KEY: "${MERCURE_SERVER_JWT_KEY}"
            DEMO: "${MERCURE_SERVER_DEMO}"
            ALLOW_ANONYMOUS: "${MERCURE_SERVER_ALLOW_ANONYMOUS}"
            HEARTBEAT_INTERVAL: "${MERCURE_SERVER_HEARTBEAT_INTERVAL}"
            ADDR: "${MERCURE_SERVER_ADDR}"
            CORS_ALLOWED_ORIGINS: "${MERCURE_SERVER_CORS_ALLOWED_ORIGINS}"
            PUBLISH_ALLOWED_ORIGINS: "${MERCURE_SERVER_PUBLISH_ALLOWED_ORIGINS}"
        ports:
            - "3000:3000"

volumes:
    container-volume: